### ISSUE TITLE
FileNotFound error

### ISSUE THREAD

**Issue by e2002e** [FSecureLABS/captcha22#14]
Hi, I downloaded captchas and converted them to png, then use captcha22 client label --input='captchasFolder' as in the readme.
I found out that I had to rename the data.zip into admin_somename_someid.zip and then launch the server otherwise I have issue #4.
But it still crashes, first there is this message:
INFO:Captcha22 Engine:Generate aocr
Illegal instruction
Illegal instruction
and a bit further (I think after I has finished training):
INFO:Captcha22 Engine:Testing training level
Traceback (most recent call last):
  File "/home/owein/.local/bin/captcha22", line 8, in <module>
    sys.exit(main())
  File "/home/owein/.local/lib/python3.9/site-packages/captcha22/__main__.py", line 278, in main
    args.func(args)
  File "/home/owein/.local/lib/python3.9/site-packages/captcha22/lib/core/server.py", line 22, in server
    server.main()
  File "/home/owein/.local/lib/python3.9/site-packages/captcha22/lib/server/captcha22.py", line 519, in main
    self.run_server()
  File "/home/owein/.local/lib/python3.9/site-packages/captcha22/lib/server/captcha22.py", line 495, in run_server
    self.continue_training()
  File "/home/owein/.local/lib/python3.9/site-packages/captcha22/lib/server/captcha22.py", line 437, in continue_training
    model.test_training_level()
  File "/home/owein/.local/lib/python3.9/site-packages/captcha22/lib/server/captcha22.py", line 130, in test_training_level
    f = open(self.path + "aocr.log")
FileNotFoundError: [Errno 2] No such file or directory: './Busy/admin/name/1/aocr.log'

I tried to touch the missing log file but then:
  File "/home/owein/.local/lib/python3.9/site-packages/captcha22/lib/server/captcha22.py", line 138, in test_training_level
    step = ast.literal_eval(values[1].split('Step ')[1].split(':')[0])
IndexError: list index out of range

Is it possible to use captcha22 from then without starting the engine but only the api server to ignore this error ?

**Comment by TinusGreen** [comment]
Hi there,

This message tells me that there is something wrong with your AOCR engine:

```
INFO:Captcha22 Engine:Generate aocr
Illegal instruction
Illegal instruction
```

AOCR generates that log file during training, which is then reviewed to determine the accuracy of the model. If the training never happened, that file would not be generated. So it won't be possible just to touch an empty file there.

Furthermore, the API is only a wrapper for the engine, if your training engine is not working, the API would not really be of any use.

You will need to figure out why AOCR is failing. The best approach would be to execute it directly.

In the directory where the captcha material is stored (in your case this should be: `./Busy/admin/name/1/`), can you please execute the following command:

`aocr train --max-height <captcha height> --max-width <captcha width> labels/training.tfrecords`

This will start a manual training process that you can control. Please post the output of that command here so I can better understand the training issue. 

If you get a core dump or seg fault, you might be facing the same issue as I did on one of my rigs where aocr fails to limit the memory usage of the GPU. We should be able to fix that, but the `Illegal Instruction` is haven't seen before, hence I'm thinking it might not be the same issue.

**Comment by e2002e** [comment]
I did so and it bails with illegal instruction, using strace:
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/librt.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\2603\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=39912, ...}) = 0
mmap(NULL, 44000, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f26b4e59000
mprotect(0x7f26b4e5c000, 24576, PROT_NONE) = 0
mmap(0x7f26b4e5c000, 16384, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3000) = 0x7f26b4e5c000
mmap(0x7f26b4e60000, 4096, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x7000) = 0x7f26b4e60000
mmap(0x7f26b4e62000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x8000) = 0x7f26b4e62000
close(3)                                = 0
mprotect(0x7f26b4e62000, 4096, PROT_READ) = 0
mprotect(0x7f26b6dfb000, 618496, PROT_READ) = 0
brk(0x11c0000)                          = 0x11c0000
brk(0x1220000)                          = 0x1220000
mprotect(0x7f26e136a000, 5808128, PROT_READ) = 0
--- SIGILL {si_signo=SIGILL, si_code=ILL_ILLOPN, si_addr=0x7f26c69a5cd0} ---
+++ killed by SIGILL +++
illegal instruction

**Comment by TinusGreen** [comment]
Hi there,

That looks like a tensorflow issue, not an AOCR issue. What version of tensorflow are you currently using? AOCR currently only supports tensorflow up to version 2.

**Comment by e2002e** [comment]
Ok I remember now that when installing tensorflow from pip I couln't find version < 2 or just don't now how to specify the version. I will report after changing that

**Comment by TinusGreen** [comment]
Hi there,

With tensorflow, you have two options. You can either use tensorflow-cpu, which then runs tensorflow on your cpu. However this is fairly slow and training times will roughly be about 40 minutes per model.

Another option is to install tensorflow-gpu, which allows tensorflow to execute on your gpu. However, this process is a bit more involved for setup, since you will probably have to build the correct tensorflow version for your system from scratch.

My suggestion would be to start with the CPU version just to test, then move to the GPU version once you get more comfortable with it.

**Comment by e2002e** [comment]
Ok, thanks.
I think tensorflow < 2 was removed from python3's packages, need to build it anyway,
