### ISSUE TITLE
getting this error "error": "Unable to base64 decode"

### ISSUE THREAD

**Issue by neelam123-a** [FSecureLABS/captcha22#16]
Hi,
once model is created. when I am following curl request to verify.

It is giving error in api response.
Unable to base64 decode.

**Comment by TinusGreen** [comment]
Hi neelam123-a,

I'll need more information that this to be able to provide guidance.

Can you please send me your full command for hosting the model and your cURL request please?

**Comment by neelam123-a** [comment]
Hi,
I have hosted model
tensorflow_model_server --port=9000 --rest_api_port=9001 --model_name=exported-model --model_base_path=/home/neelam.singh/Desktop/captcha_breaker/ .
![Screenshot from 2021-05-11 16-46-08](https://user-images.githubusercontent.com/72464887/117806978-a3de3300-b278-11eb-9d28-e838ae28a0f4.png)


cURL request to verify
![Screenshot from 2021-05-11 16-46-56](https://user-images.githubusercontent.com/72464887/117807185-e7d13800-b278-11eb-8e07-a4e733b4efcc.png)

please help.

**Comment by TinusGreen** [comment]
Hi neelam123-a,

`/9j/4AAQ==` can't be the entire image. Usually that image string is roughly 100 - 300 characters long?

From where did you pull that image string? To verify that the string is correct, you should be able to base64 decode it to binary data and save as png. If you can see the actual image, that means that it is working.

**Comment by neelam123-a** [comment]
Hi,
Thankyou...
I wanted to know that once model is hosted on tensorflow...then how will I verify that model is working? 
please help.

**Comment by neelam123-a** [comment]
and also when i am connecting to 
captcha22 client api...
when I opt option 6 : activate a server-side Captcha model
I am getting this error..
![Uploading Screenshot from 2021-05-11 20-20-50.png…]()

**Comment by neelam123-a** [comment]
Hi
![Screenshot from 2021-05-11 20-20-50](https://user-images.githubusercontent.com/72464887/117928170-cb84d800-b318-11eb-918c-ab109f50a73b.png)
,
also when i am connecting to
captcha22 client api...
when I opt option 6 : activate a server-side Captcha model
I am getting this error.

**Comment by TinusGreen** [comment]
Hi neelam123-a,

In terms of how you test if the model is working, you need to send it a captcha image, like you are doing with cURL, but it requires the full base64 encoded image. Should it be a full image, tensorflow will respond with what it thinks the text it as well as an accuracy rating. This will help you verify that the model is working.

However, you should already have indicative results. If you used the API to upload the images for training, you can use the client API to query stats about the model using option [2] and then providing your captcha ID which is your case is `1`.

In terms of the issue that you are having activating the model client side, I'll have a look and see if I can replicate the issue.

**Comment by neelam123-a** [comment]
Hi,
Thankyou so much for your response..

**Comment by neelam123-a** [comment]
Hi TinusGreen,
I am trying to connect captcha22 client api.. but getting this error whenever try to activate a sever side captcha model.
please resolve this issue.. though i am able to extract model but failing to activate.
![Screenshot from 2021-05-11 20-20-50](https://user-images.githubusercontent.com/72464887/118966737-82233100-b987-11eb-9766-cdda2fd70244.png)

**Comment by GEkuL** [comment]
@TinusGreen hi, exactly the same, as mentioned above, goes for me. Please fix this in the future updates!

**Comment by TinusGreen** [comment]
Hi Neelam123-a, the issue mentioned above has been resolved in version 1.0.7. Seems like one of the log inputs was not parsing correctly.
